### ISSUE TITLE
loading style.css twice

### ISSUE THREAD

**Issue by matthijsbro** [craftwerkberlin/bootscore-5-child#2]
This functions.php in child-theme loads my style.css twice. 
With id 'bootscore-style-css' and with id 'child-theme-css-css'. I can just comment out the second: `
wp_enqueue_style( 'child-theme-css', get_stylesheet_directory_uri() .'/style.css' , array('parent-style'));`
and it works fine. 

<img width="265" alt="Screenshot 2021-03-07 at 15 25 43" src="https://user-images.githubusercontent.com/803217/110243183-972c1e80-7f59-11eb-85e8-79389b9da125.png">

**Comment by craftwerkberlin** [comment]
Please check what the style.css does in every WP theme https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/

**Comment by matthijsbro** [comment]
bootscore parent functions.php uses 

`	
wp_enqueue_style( 'bootscore-style', get_stylesheet_uri() ); 
`

get_stylesheet_uri() looks for child-theme style.css first. 

The child-theme functions.php loads:

`		wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' );
		wp_enqueue_style( 'child-theme-css', get_stylesheet_directory_uri() .'/style.css' , array('parent-style'));
`

The second line is then obsolete? Because in my html I now find: 
parent-style-css (the parent style.css loaded from child's functions.php)
child-theme-css-css (the child style.css loaded from child's functions.php)
bootscore-style-css (the child style.css loaded from parent functions.php)


```
<link rel='stylesheet' id='wp-block-library-css'  href='https://localhost:8443/mf/wp-includes/css/dist/block-library/style.min.css?ver=5.6.2' type='text/css' media='all' />
<link rel='stylesheet' id='parent-style-css'  href='https://localhost:8443/mf/wp-content/themes/bootscore-5/style.css?ver=5.6.2' type='text/css' media='all' />
<link rel='stylesheet' id='child-theme-css-css'  href='https://localhost:8443/mf/wp-content/themes/bootscore-5-child/style.css?ver=5.6.2' type='text/css' media='all' />
<link rel='stylesheet' id='bootstrap-css'  href='https://localhost:8443/mf/wp-content/themes/bootscore-5/css/lib/bootstrap.min.css?ver=5.6.2' type='text/css' media='all' />
<link rel='stylesheet' id='bootscore-style-css'  href='https://localhost:8443/mf/wp-content/themes/bootscore-5-child/style.css?ver=5.6.2' type='text/css' media='all' />

```

**Comment by craftwerkberlin** [comment]
I see, child style.css is loaded twice. I will check it. Thnx for reporting

**Comment by craftwerkberlin** [comment]
You're right. Changed the enqueue code and updated the theme. Thnx for reporting.

`	// style.css
	 add_action( 'wp_enqueue_scripts', 'bootscore_5_child_enqueue_styles' );
	 function bootscore_5_child_enqueue_styles() {
 		  wp_enqueue_style( 'parent-style', get_template_directory_uri() . '/style.css' ); 
 		  } `
