### ISSUE TITLE
Sticky footer

### ISSUE THREAD

**Issue by norico** [craftwerkberlin/bootscore-5-child#3]
Request sticky footer 

I try to set footer at bottom of page but my-auto on footer doesn’t work

**Comment by craftwerkberlin** [comment]
my-auto is for vertical margin not for positioning. You can add class fixed-bottom to make element sticky at the bottom of the page.

**Comment by norico** [comment]
Fixed bottom doesn’t work, footer stay over post content on small windows size. 
Margin top auto (mt-auto) on flex item is correct on bootstrap html classic theme. 
sorry for my-auto (mobile phone auto correct)

**Comment by craftwerkberlin** [comment]
Can you please share a link to your site and explain again exactly what you want to do? I must understand it on example.

**Comment by norico** [comment]
Ok it’s resolved
I just add a filter on language attribute and some classes. 
I send patch this afternoon (can’t write code on mobile phone)

**Comment by norico** [comment]
`/* Add your styles here */
html {
    height: 100vh;
}
html.admin-bar {
    height: calc( 100vh - 32px );
}
@media (max-width: 767px) {
    html.admin-bar {
        height: calc( 100vh - 46px );
    }
}
body {
    height: 100%;
}
#page {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    height: 100%;
}
#content {
    min-height: auto;
}
footer {
    margin-top: auto !important;
}`

---

`
// admin-bar Flex Adjust
add_filter('language_attributes', 'bootscore_5_footer_adjust');
function bootscore_5_footer_adjust($lang) :string{
    if( is_user_logged_in() )
        $lang = $lang . 'class="admin-bar"';
    return $lang;

}
`

**Comment by craftwerkberlin** [comment]
Do you have a live preview?

**Comment by norico** [comment]
I just created the plugin to push the footer in the footer. 
You are free to test it.
https://github.com/norico/BtScore-Footer-Adjust

**Comment by crftwrk** [comment]
Why you deleted the link to your plugin? I would reopen this issue and transfer it to parent-theme's issues. So users can load it if they want to use a sticky footer. I like your plugin.
