### ISSUE TITLE
MIME type 

### ISSUE THREAD

**Issue by matthijsbro** [craftwerkberlin/bootscore-5-child#7]
Is this a server thing or a theme thing? Since the fresh Wordpress install and default theme work I would think the latter. 

`Refused to apply style from '..[domain]./bootscore-child-main/css/lib/bootstrap.min.css?ver=197001010000' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

in the header it is just

`<link rel="stylesheet" id="bootstrap-css" href=".[domain]./bootscore-child-main/css/lib/bootstrap.min.css?ver=197001010000" type="text/css" media="all">`

**Comment by matthijsbro** [comment]
https://dl.dzjindag.nl/ 
Love to hear if you get this. Could be something in server config I guess.

**Comment by crftwrk** [comment]
Hmm... styles and scripts are not loaded but themes are latest versions. Can you please try another server? Just for testing.
